apiVersion: apps/v1
kind: Deployment
metadata:
  name: brain-tasks-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: brain-tasks
  template:
    metadata:
      labels:
        app: brain-tasks
    spec:
      containers:
        - name: brain-tasks
          image: 992757690557.dkr.ecr.us-east-1.amazonaws.com/miniproject1/braintask:latest
          ports:
            - containerPort: 80
