apiVersion: apps/v1
kind: Deployment
metadata:
  name: brain-tasks-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: brain-tasks
  template:
    metadata:
      labels:
        app: brain-tasks
    spec:
      containers:
        - name: brain-tasks
          image: public.ecr.aws/s2i0y8i2/brain-task-app:latest
          ports:
            - containerPort: 80
      imagePullSecrets:
        - name: ecr-creds
